import MainLayout from "../layouts/MainLayout";

export default function TermsAndConditions() {
    return (
        <MainLayout>
            <section className="py-20 bg-white">
                <div className="max-w-4xl mx-auto px-4 md:px-6">

                    {/* Title */}
                    <h1 className="pt-10 text-3xl md:text-4xl font-bold mb-6">
                        Terms & Conditions
                    </h1>

                    <p className="text-gray-600 mb-10">
                        These Terms & Conditions govern your access to and use of the
                        Wellness Solution application and website. By using our services,
                        you agree to comply with these terms. If you do not agree, please
                        refrain from using the platform.
                    </p>

                    {/* Acceptance */}
                    <Section title="Acceptance of Terms">
                        <p>
                            By accessing or using Wellness Solution, you confirm that you have
                            read, understood and agreed to these Terms & Conditions. These
                            terms apply to all users of the application and website.
                        </p>
                    </Section>

                    {/* Purpose */}
                    <Section title="Purpose of the Application">
                        <p>
                            Wellness Solution is designed to provide health-related guidance,
                            symptom-based insights and general wellness information to help
                            users make informed decisions about their health.
                        </p>

                        <p>
                            The information provided by Wellness Solution is for educational
                            and informational purposes only and should not be considered a
                            substitute for professional medical advice, diagnosis or
                            treatment.
                        </p>
                    </Section>

                    {/* Medical Disclaimer */}
                    <Section title="Medical Disclaimer">
                        <p>
                            Wellness Solution does not provide medical diagnoses or treatment.
                            The predictions, recommendations and insights generated by the
                            app are based on user-provided information and medical reference
                            sources.
                        </p>

                        <p>
                            Always seek the advice of a qualified healthcare professional
                            regarding any medical condition or treatment. Do not ignore
                            professional medical advice based on information obtained from
                            this application.
                        </p>
                    </Section>

                    {/* User Responsibilities */}
                    <Section title="User Responsibilities">
                        <ul className="list-disc pl-6 text-gray-600 space-y-2">
                            <li>Provide accurate and complete information when using the app</li>
                            <li>Use the application only for lawful purposes</li>
                            <li>Not misuse, copy or attempt to reverse engineer the platform</li>
                            <li>Maintain the confidentiality of account access credentials</li>
                        </ul>
                    </Section>

                    {/* Account Usage */}
                    <Section title="Account Usage">
                        <p>
                            Users are responsible for maintaining the security of their
                            account and all activities performed under their account. Any
                            unauthorized use should be reported immediately.
                        </p>

                        <p>
                            Wellness Solution reserves the right to suspend or terminate
                            accounts found to be in violation of these Terms & Conditions.
                        </p>
                    </Section>

                    {/* Intellectual Property */}
                    <Section title="Intellectual Property">
                        <p>
                            All content, features, designs, logos and intellectual property
                            associated with Wellness Solution are owned by or licensed to
                            Wellness Solution.
                        </p>

                        <p>
                            Users may not reproduce, distribute, modify or create derivative
                            works without prior written permission.
                        </p>
                    </Section>

                    {/* Third-Party Services */}
                    <Section title="Third-Party Services">
                        <p>
                            Wellness Solution may integrate third-party services such as
                            notification providers or analytics tools to improve user
                            experience.
                        </p>

                        <p>
                            We are not responsible for the content, policies or practices of
                            third-party services. Use of such services is subject to their
                            respective terms.
                        </p>
                    </Section>

                    {/* Limitation of Liability */}
                    <Section title="Limitation of Liability">
                        <p>
                            Wellness Solution shall not be liable for any direct, indirect,
                            incidental or consequential damages arising from the use or
                            inability to use the application or website.
                        </p>

                        <p>
                            Use of the platform is at your own risk.
                        </p>
                    </Section>

                    {/* Termination */}
                    <Section title="Termination">
                        <p>
                            We reserve the right to suspend or terminate access to Wellness
                            Solution at any time, without prior notice, if these Terms &
                            Conditions are violated.
                        </p>
                    </Section>

                    {/* Changes */}
                    <Section title="Changes to Terms">
                        <p>
                            We may update these Terms & Conditions from time to time. Any
                            changes will be effective immediately upon posting.
                        </p>

                        <p>
                            Continued use of the application after changes constitutes
                            acceptance of the updated terms.
                        </p>
                    </Section>

                    {/* Contact */}
                    <Section title="Contact Information">
                        <p>
                            If you have any questions regarding these Terms & Conditions,
                            please contact us through the Contact page. We are committed to
                            addressing your concerns promptly.
                        </p>
                    </Section>

                </div>
            </section>
        </MainLayout>
    );
}

/* ------------------ Helper Components ------------------ */

function Section({ title, children }: { title: string; children: React.ReactNode }) {
    return (
        <div className="mb-12">
            <h2 className="text-xl md:text-2xl font-semibold mb-4">{title}</h2>
            <div className="text-gray-600 space-y-4">{children}</div>
        </div>
    );
}
